# Generated by Django 3.2.4 on 2021-07-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('goods', '0002_auto_20210621_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='goods'),
        ),
    ]
