# Generated by Django 3.2.4 on 2021-07-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('goods', '0006_auto_20210712_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='vendors'),
        ),
    ]
