# BUILD THIS APP:
# $ docker compose up -d --build
# go to your localhost http://0.0.0.0:8000/

version: "3"

services:
  django-app:
    build:
      context: ./django_ecommerce
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    environment:
      DEBUG: 'true'
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dj_docker

volumes:
  postgres_data:
