# Generated by Django 3.2.5 on 2021-07-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210720_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='vendors'),
        ),
    ]
