# Generated by Django 3.2.4 on 2021-07-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('goods', '0004_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
