# Generated by Django 3.2.5 on 2021-08-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210818_1439'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='user_order',
            field=models.ManyToManyField(to='main.Order'),
        ),
    ]
